const EMAIL_PASS = '!@#$%QWERT';
const { PORT, ROOT } = require('../app');
// indexController
const DEFAULT_PRODUCTS_SORT_ORDER = 'newest';
const MAX_SEARCH_INPUT_LEN = 100;
const MIN_SEARCH_INPUT_LEN = 1;
const HOMEPAGE_PRODUCTS_LIMIT = 40;
const RECORDS_PER_PAGE = 40;
const MAX_RECORDS_PER_PAGE = 100;
// usersController
const MAX_USER_EMAIL_LEN = 50;
const MIN_USER_EMAIL_LEN = 5;
const MAX_USER_PASSWORD_LEN = 255;
const MIN_USER_PASSWORD_LEN = 8;
const MAX_USER_NAME_LEN = 20;
const MIN_USER_NAME_LEN = 2;
const MAX_COUNTRY_LEN = 64;
const MIN_COUNTRY_LEN = 2;
const MAX_REGION_LEN = 64;
const MIN_REGION_LEN = 2;
const MAX_STREET_ADDRESS_LEN = 64;
const MIN_STREET_ADDRESS_LEN = 2;
const CONNECTION_LIMIT = 1000;
const SERVICE_EMAIL = 'vanime.staff@gmail.com';
const SERVICE_EMAIL_PROVIDER = 'gmail';
// backOfficeController
const ORDER_STATUSES_QUERY_LIMIT = 10000;
const MAX_USERNAME_LEN = 20;
const MAX_SEARCH_FILTER_LEN = 50;

module.exports = {
  EMAIL_PASS: EMAIL_PASS,
  PORT: PORT,
  ROOT: ROOT,
  DEFAULT_PRODUCTS_SORT_ORDER: DEFAULT_PRODUCTS_SORT_ORDER,
  MAX_SEARCH_INPUT_LEN: MAX_SEARCH_INPUT_LEN,
  MIN_SEARCH_INPUT_LEN: MIN_SEARCH_INPUT_LEN,
  HOMEPAGE_PRODUCTS_LIMIT: HOMEPAGE_PRODUCTS_LIMIT,
  RECORDS_PER_PAGE: RECORDS_PER_PAGE,
  MAX_RECORDS_PER_PAGE: MAX_RECORDS_PER_PAGE,
  MAX_USER_EMAIL_LEN: MAX_USER_EMAIL_LEN,
  MIN_USER_EMAIL_LEN: MIN_USER_EMAIL_LEN,
  MAX_USER_PASSWORD_LEN: MAX_USER_PASSWORD_LEN,
  MIN_USER_PASSWORD_LEN: MIN_USER_PASSWORD_LEN,
  MAX_USER_NAME_LEN: MAX_USER_NAME_LEN,
  MIN_USER_NAME_LEN: MIN_USER_NAME_LEN,
  MAX_COUNTRY_LEN: MAX_COUNTRY_LEN,
  MIN_COUNTRY_LEN: MIN_COUNTRY_LEN,
  MAX_REGION_LEN: MAX_REGION_LEN,
  MIN_REGION_LEN: MIN_REGION_LEN,
  MAX_STREET_ADDRESS_LEN: MAX_STREET_ADDRESS_LEN,
  MIN_STREET_ADDRESS_LEN: MIN_STREET_ADDRESS_LEN,
  CONNECTION_LIMIT: CONNECTION_LIMIT,
  SERVICE_EMAIL: SERVICE_EMAIL,
  SERVICE_EMAIL_PROVIDER: SERVICE_EMAIL_PROVIDER,
  ORDER_STATUSES_QUERY_LIMIT: ORDER_STATUSES_QUERY_LIMIT,
  MAX_USERNAME_LEN: MAX_USERNAME_LEN,
  MAX_SEARCH_FILTER_LEN: MAX_SEARCH_FILTER_LEN
};
